### ISSUE TITLE
{request} add windows media keys control

### ISSUE THREAD

**Issue by sp0ok3r** [AlirezaKJ/BetterSoundCloud#12]
add windows media keys control

**Comment by AlirezaKJ** [comment]
working on it

**Comment by AlirezaKJ** [comment]
feature added at commit https://github.com/AlirezaKJ/BetterSoundCloud/commit/7146c5770e281353a548c47debfa9e997da17774 (available at latest fetched manual installation)
will also be available at next auto installers release happening with the website remake
