### ISSUE TITLE
Next/Previous Track only works for the first track

### ISSUE THREAD

**Issue by SAMDestroy** [AlirezaKJ/BetterSoundCloud#14]
Hello,
thanks for your desktop app. im trying to implement it to stream deck.
im using the media keys to skip to next/previous track but this is only working for one track.
the skip next/previous is not working anymore after listen to a whole track.
is this maybe because of the adblock?

**Comment by AlirezaKJ** [comment]
media keys are now more effective using electron Globalshortcuts at latest update which just released.
download from:
https://github.com/AlirezaKJ/BetterSoundCloud/releases/tag/V0.5.3
implemented at:
https://github.com/AlirezaKJ/BetterSoundCloud/commit/7146c5770e281353a548c47debfa9e997da17774

**Comment by SAMDestroy** [comment]
thanks for the fast release.
it seems the next/prev mediakeys do work now but
i have no systray icon.
the new global mediakeys dosent work if an other app is fullscreen.

**Comment by AlirezaKJ** [comment]
try to fix the tray icon by next week, and find another solution for media keys as well

**Comment by AlirezaKJ** [comment]
the executables and installers for version 0.5.3 just got updated and renewed with few fixes for tray icon, and bunch of other loading issues with different themes. check it out by reinstalling 0.5.3

https://github.com/AlirezaKJ/BetterSoundCloud/releases/tag/V0.5.3
