### ISSUE TITLE
Not a soundcloud url!

### ISSUE THREAD

**Issue by gLukah** [AlirezaKJ/BetterSoundCloud#15]
i tried sing in with my google account but there was a error login in, then when i clicked log in again a message popped up saying i was blocked (i wasnt banned or something like that since i can still log in on the normal page) then when i relaunched bettersoundcloud i had a error saying "not a Soundcloud url!" and it closes right after that. i dont know why this happens tbh.
![Screenshot_1](https://github.com/AlirezaKJ/BetterSoundCloud/assets/72108571/02a5e8a3-ceaf-456f-9197-ba4b8a72e527)

**Comment by AlirezaKJ** [comment]
it is mainly because u still have bettersoundcloud open on the background and u should open it from the tray button by double clicking the icon in the tray and you will be fine

**Comment by aliemamidev** [comment]
have you ever tried a feature akin to Incognito Mode, such as Google Incognito or  Edge Incognito? 
FYI this should be fine as it's not gonna directly link to external software.
