### ISSUE TITLE
you site need update!

### ISSUE THREAD

**Issue by aliemamidev** [AlirezaKJ/BetterSoundCloud#16]
Hey my old friend Looks like there's a glitch in  your site https://alirezakj.com/bsc/. Those icons (which are in image format) aren't loading properly The root of the issue seems to be that the images were uploaded to Discord, and then their links were used on the site. Discord, however, changes all content links periodically to prevent its use as an upload center, which is why those images are MIA on your site.

![image](https://github.com/AlirezaKJ/BetterSoundCloud/assets/83456973/6678ca83-a042-4bde-8ad4-0a39a4eed997)

![image](https://github.com/AlirezaKJ/BetterSoundCloud/assets/83456973/f3275745-6055-47f9-aece-f1e89ca4188b)

**Comment by AlirezaKJ** [comment]
it will be fixed ASAP by release of the reworked website in progress and im aware of the issue, thanks for reminding me.
