### ISSUE TITLE
why is it using older electron?

### ISSUE THREAD

**Issue by dxcvvxd** [AlirezaKJ/BetterSoundCloud#20]
my issue here is i'd like to know why exactly is it using electron 22 and would it be possible to make it use the newest one
i'm just worried about having to keep 2 different electrons instead of 1, it just seems unnecessary

**Comment by AlirezaKJ** [comment]
Hi, thanks for the issue there wasn't any reason for the old electron version technically, I just didn't pay the attention i needed to the npm LOGS. electron has been updated to the latest version at below commit.

https://github.com/AlirezaKJ/BetterSoundCloud/commit/718f49c3286504cf2cf4a5ed1c79f118e704564c
