### ISSUE TITLE
Not a Soundcloud URL

### ISSUE THREAD

**Issue by Aterox-os** [AlirezaKJ/BetterSoundCloud#22]
After the first start which works just fine, I get the error "Not a SoundCloud URL" every time I try to start the program.

**Comment by AlirezaKJ** [comment]
as referred in the previous issue https://github.com/AlirezaKJ/BetterSoundCloud/issues/15

you need to open the app through the tray icon or putting bsc://soundcloud.com/mahdyar/sets/hagh (or anyother soundcloud link with the https replaced by bsc)
