### ISSUE TITLE
mark / hide played tracks

### ISSUE THREAD

**Issue by flotterfrank** [AlirezaKJ/BetterSoundCloud#4]
A great feature would be marking previously played titles as played or hiding them. I'm only interested in new titles or reposts, e.g. at https://soundcloud.com/feed. But often there are also reposts of titles that i have already played.

It should be possible to store the address of the currently played track in a database or index. The link to the address to the track is at the bottom right when a track is played. When a feed is shown, you should compare the addresses of the tracks with those in the database or index and mark or hide the corresponding entries.

**Comment by AlirezaKJ** [comment]
its gonna be a tough thing but still try on to add it on the new release
thanks for the idea ;)

**Comment by flotterfrank** [comment]
Thank you for considering my request and for already starting with it. The difficulty might be to get it performing well with many songs already played. I get about 50 songs a day in my feed that I listen to. If there are playlists in the stream, there are a few more songs. The list of played songs grows very quickly. Hiding playlists or individual songs from them in the feed could not be trivial either.

**Comment by AlirezaKJ** [comment]
unfortunately i cant deal with it right now its gonna be tough but i hold it on for later fixes
