### ISSUE TITLE
add minimize to system tray

### ISSUE THREAD

**Issue by sp0ok3r** [AlirezaKJ/BetterSoundCloud#9]
add minimize to system tray 😤😤

**Comment by AlirezaKJ** [comment]
working on it, new release soon.

**Comment by AlirezaKJ** [comment]
feature implemented on below commit which is available on manual installation, will be available on app installers at next build.

https://github.com/AlirezaKJ/BetterSoundCloud/commit/db0b5e423043ca04b39c67a35d137a002e360a60
